# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=128, unique=True)),
                ('Introduction', models.TextField()),
                ('colour', models.CharField(max_length=128, unique=True)),
                ('smell', models.TextField()),
                ('taste', models.TextField()),
                ('After', models.CharField(max_length=128, unique=True)),
                ('cask', models.TextField()),
            ],
        ),
    ]
