# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(max_length=128, unique=True)),
                ('payment', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
