# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
