# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
