# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productimg',
            field=models.ImageField(default=django.utils.timezone.now, height_field=375, upload_to='', width_field=372),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='titleimg',
            field=models.ImageField(default=django.utils.timezone.now, height_field=375, upload_to='', width_field=372),
            preserve_default=False,
        ),
    ]
