# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180112_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ename',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
